# Generated by Django 5.0 on 2025-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('referral', models.CharField(blank=True, max_length=100)),
                ('handphone', models.CharField(max_length=20)),
                ('join_date', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
                ('file_type', models.CharField(max_length=20)),
                ('error_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'upload_time'], name='data_manage_tenant__a7d935_idx')],
                'unique_together': {('tenant_id', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('Deposit', 'Deposit'), ('Manual Deposit', 'Manual Deposit'), ('Withdraw', 'Withdraw'), ('Manual Withdraw', 'Manual Withdraw')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateTimeField()),
                ('process_date', models.DateTimeField()),
                ('process_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('username', 'event', 'create_date', 'amount')},
            },
        ),
    ]
