# Generated by Django 5.0 on 2025-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('referral', models.CharField(blank=True, max_length=100)),
                ('handphone', models.CharField(max_length=20)),
                ('join_date', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateTimeField()),
                ('process_date', models.DateTimeField()),
                ('process_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('username', 'event', 'create_date', 'amount')},
            },
        ),
    ]
