# Generated by Django 5.0 on 2025-07-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('file_path', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
                ('file_type', models.CharField(max_length=20)),
                ('error_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
            ],
        ),
    ]
