# Generated by Django 5.0 on 2025-08-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_errorlog'),
        ('tenants', '0002_alter_tenant_options_tenant_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
