# Generated by Django 5.0 on 2025-08-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_errorlog_tenant'),
    ]

    operations = [
    ]
