# Generated by Django 5.0 on 2025-08-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_auto_20250802_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='tenant',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='tenant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
