# Generated by Django 5.0 on 2025-08-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_remove_errorlog_tenant_errorlog_tenant_id'),
    ]

    operations = [
    ]
