# Generated by Django 5.0 on 2025-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_auto_20250802_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
