# Generated by Django 5.0 on 2025-08-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_auto_20250803_0611'),
    ]

    operations = [
    ]
