# Generated by Django 5.0 on 2025-08-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_auto_20250803_0611'),
        ('tenants', '0002_alter_tenant_options_tenant_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
