# Generated by Django 5.0 on 2025-08-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_remove_errorlog_tenant_id_errorlog_tenant'),
        ('tenants', '0002_alter_tenant_options_tenant_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
