# Generated by Django 5.0 on 2025-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Unique identifier for the tenant (e.g., pukul69)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name of the tenant/customer', max_length=100)),
                ('db_alias', models.CharField(help_text='Database alias from settings (e.g., crm_db_pukul69)', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True, help_text='Date the tenant was created')),
            ],
        ),
    ]
