# Generated by Django 5.0 on 2025-07-29 01:23

import django.utils.timezone
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-subscription_end']},
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable tenant access'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end',
            field=models.DateField(default=tenants.models.one_month_from_today, help_text='Subscription expiration date'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Subscription start date'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='db_alias',
            field=models.CharField(help_text='Database alias from settings', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(help_text='Unique identifier for the tenant', max_length=100, unique=True),
        ),
    ]
