"""
Django settings for crm_system project.

Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = '/accounts/login/'
#LOGIN_REDIRECT_URL = '/dashboard/'
#LOGOUT_REDIRECT_URL = '/dashboard/'

LOGIN_REDIRECT_URL = 'tenant_redirect'  # We'll create this view
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Add this to redirect authenticated users away from login page
AUTHENTICATED_REDIRECT_URL = 'tenant_redirect'


# Security settings
SECRET_KEY = 'django-insecure-4r)r(q=0d3zpjm+3x&+5z)0_#0z1rd3wud+w+u_^ub--i5%2*8'
DEBUG = False    

# Custom error handlers
handler404 = 'crm_system.views.custom_404'
#handler500 = 'crm_system.views.custom_500'


ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'data_management',
    'dashboard_app',
    'report_app',
    'tenants', 
    'tenant_management',
    'whatsapp_messaging'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.BackendSessionMiddleware',
    'tenants.middleware.TenantBypassMiddleware',
    'tenants.middleware.TenantMiddleware',  # Your custom middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenants.middleware.ResponseSafetyMiddleware',
    'tenants.middleware.SecurityLoggerMiddleware',
    'tenants.subscription_middleware.SubscriptionMiddleware',   
]

ROOT_URLCONF = 'crm_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_system.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crm_db',
        'USER': 'crm_user',
        'PASSWORD': 'securepassword',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public'  # Add this line
        },
    },

    'crm_db_pukul_com': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crm_db_pukul_com',
        'USER': 'crm_user',
        'PASSWORD': 'securepassword',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public'  # Add this line
        },
    },
    'crm_db_test_com': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crm_db_test_com',
        'USER': 'crm_user',
        'PASSWORD': 'securepassword',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public'  # Add this line
        },
    },
    
}

# Database router for tenant isolation
DATABASE_ROUTERS = ['tenants.db_router.DatabaseTenantRouter']

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'tenants.backends.TenantAuthBackend',
    #'django.contrib.auth.backends.ModelBackend',
]



# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Add if you have static files directory

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Use database-backed sessions
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Verify cookie settings
SESSION_COOKIE_SECURE = False #Set True in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = "crm_session"

# crm_system/settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'tenants': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Add session settings
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 3600  # 1 hour

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '172.23.5.133', '100.122.81.22', '100.121.155.33']

PUBLIC_APPS = ['admin', 'auth', 'contenttypes', 'sessions', 'tenants']

AUTH_USER_MODEL = "auth.User" # Just to make sure it's here

# WhatsApp Evolution API Configuration
EVOLUTION_API_CONFIG = {
    'BASE_URL': 'http://localhost:8081',
    'API_KEY': '429683C4C977415CAAFCCE10F7D57E11',  # Your actual API key
    'WEBHOOK_URL': 'http://localhost:8000/api/whatsapp/webhooks/evolution/',
    'DEFAULT_TIMEOUT': 30,
    'MAX_INSTANCES': 20,
    'DEFAULT_MESSAGE_LIMIT': 200,  # Per instance per day
}

# Message Queue Settings
MESSAGE_QUEUE_CONFIG = {
    'MAX_RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 300,  # 5 minutes
    'BATCH_SIZE': 50,  # Messages per batch
    'RATE_LIMIT_PER_INSTANCE': 50,  # Messages per hour per instance
}
