# Generated by Django 5.0 on 2025-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaudience',
            name='verification_cache_days',
            field=models.IntegerField(default=14, help_text='Days to cache WhatsApp verification results'),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='verification_completed_at',
            field=models.DateTimeField(blank=True, help_text='When WhatsApp verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='verification_started_at',
            field=models.DateTimeField(blank=True, help_text='When WhatsApp verification was started', null=True),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='whatsapp_error_count',
            field=models.IntegerField(default=0, help_text='Numbers that failed verification due to errors'),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='whatsapp_not_found_count',
            field=models.IntegerField(default=0, help_text="Numbers that don't have WhatsApp"),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='whatsapp_pending_count',
            field=models.IntegerField(default=0, help_text='Numbers not yet verified'),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='whatsapp_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'Verifying...'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='not_started', help_text='Status of WhatsApp number verification for this audience', max_length=20),
        ),
        migrations.AddField(
            model_name='customaudience',
            name='whatsapp_verified_count',
            field=models.IntegerField(default=0, help_text='Numbers confirmed to have WhatsApp'),
        ),
    ]
