# Generated by Django 5.0 on 2025-09-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0002_add_whatsapp_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='include_non_whatsapp',
            field=models.BooleanField(default=False, help_text='Include numbers without WhatsApp'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='include_whatsapp_verified',
            field=models.BooleanField(default=True, help_text='Include numbers confirmed to have WhatsApp'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='whatsapp_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Has WhatsApp'), ('not_available', 'No WhatsApp'), ('unknown', 'Not Verified')], help_text='WhatsApp verification status at time of campaign', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='include_unverified_numbers',
            field=models.BooleanField(default=False, help_text='Include numbers with unknown WhatsApp status'),
        ),
    ]
