# Generated by Django 5.0 on 2025-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0003_campaign_include_non_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntarget',
            name='whatsapp_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Has WhatsApp'), ('not_available', 'No WhatsApp'), ('unknown', 'Not Verified')], default='unknown', help_text='WhatsApp verification status at time of campaign', max_length=20),
        ),
        migrations.AlterField(
            model_name='phonenumberhistory',
            name='whatsapp_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('confirmed', 'Has WhatsApp'), ('not_available', 'No WhatsApp'), ('blocked', 'Blocked/Banned'), ('invalid', 'Invalid Number'), ('timeout', 'Verification Timeout'), ('request_error', 'Verification Error'), ('api_error_500', 'API Error')], default='unknown', max_length=20),
        ),
    ]
