# Generated by Django 5.0 on 2025-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0004_alter_campaigntarget_whatsapp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='instance_strategy',
            field=models.CharField(blank=True, choices=[('random_pool', 'Random Pool Rotation'), ('round_robin', 'Round Robin'), ('single_instance', 'Single Instance')], default='random_pool', help_text='How to distribute messages across WhatsApp instances', max_length=20),
        ),
    ]
