# Generated by Django 5.0 on 2025-09-30 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_campaigns', '0005_campaign_instance_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstanceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(db_index=True, help_text='WhatsApp instance identifier', max_length=100, unique=True)),
                ('messages_sent_today', models.IntegerField(default=0, help_text='Messages sent today (resets at midnight)')),
                ('messages_sent_this_hour', models.IntegerField(default=0, help_text='Messages sent in current hour')),
                ('last_message_sent_at', models.DateTimeField(blank=True, help_text='When last message was sent', null=True)),
                ('is_in_cooldown', models.BooleanField(default=False, help_text='Is instance currently in cooldown')),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='When cooldown ends', null=True)),
                ('last_used_position', models.IntegerField(default=0, help_text='Last position in round-robin rotation')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Consecutive send failures')),
                ('total_messages_sent', models.IntegerField(default=0, help_text='Total lifetime messages')),
                ('total_failures', models.IntegerField(default=0, help_text='Total lifetime failures')),
                ('last_hourly_reset', models.DateTimeField(default=django.utils.timezone.now, help_text='When hourly counter was reset')),
                ('last_daily_reset', models.DateTimeField(default=django.utils.timezone.now, help_text='When daily counter was reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Instance Usage',
                'verbose_name_plural': 'WhatsApp Instance Usage',
                'db_table': 'marketing_whatsapp_instance_usage',
            },
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='auto_disable_failed_instances',
            field=models.BooleanField(default=True, help_text='Automatically disable instances with repeated failures'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='failure_threshold',
            field=models.IntegerField(default=5, help_text='Consecutive failures before disabling instance'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='instance_cooldown_minutes',
            field=models.IntegerField(default=15, help_text='Minutes to wait before reusing an instance'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='instance_selection_strategy',
            field=models.CharField(choices=[('round_robin', 'Round Robin - Rotate evenly'), ('random', 'Random Selection'), ('least_used', 'Least Used First')], default='round_robin', help_text='How to select WhatsApp instances for campaigns', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='max_delay_seconds',
            field=models.IntegerField(default=180, help_text='Maximum seconds between messages'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='max_messages_per_hour_global',
            field=models.IntegerField(default=20, help_text='Maximum messages per hour across all instances'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='max_messages_per_instance_day',
            field=models.IntegerField(default=200, help_text='Maximum messages per day per single instance'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='max_messages_per_instance_hour',
            field=models.IntegerField(default=10, help_text='Maximum messages per hour per single instance'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='min_delay_seconds',
            field=models.IntegerField(default=60, help_text='Minimum seconds between messages'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='rotate_after_messages',
            field=models.IntegerField(default=50, help_text='Switch instance after X messages'),
        ),
        migrations.AddField(
            model_name='tenantcampaignsettings',
            name='use_random_delays',
            field=models.BooleanField(default=True, help_text='Randomize delays for more human-like behavior'),
        ),
    ]
