# Generated by Django 5.0 on 2025-09-21 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, help_text='The ID of the tenant this WhatsApp instance belongs to.')),
                ('instance_name', models.CharField(help_text='Unique name for this WhatsApp instance within the tenant.', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='Unique ID from the external WhatsApp API (e.g., Evolution API).', max_length=255, null=True)),
                ('api_key', models.CharField(default='', help_text='The API key or access token for this instance.', max_length=255)),
                ('phone_number', models.CharField(help_text='WhatsApp business phone number.', max_length=20)),
                ('owner_jid', models.CharField(blank=True, help_text='WhatsApp JID from the external API.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('closed', 'Closed')], default='disconnected', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='Base64 QR code for authentication.', null=True)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Session information from the external API.')),
                ('daily_message_limit', models.PositiveIntegerField(default=1000, help_text='Daily message sending limit.')),
                ('daily_message_count', models.PositiveIntegerField(default=0, help_text='Messages sent today.')),
                ('last_message_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with the external API.', null=True)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_instances',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'instance_name')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of webhook event.', max_length=50)),
                ('evolution_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Raw webhook data from Evolution API.')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_instance', models.ForeignKey(blank=True, help_text='The WhatsApp instance this event is related to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_messaging.whatsappinstance')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed', 'created_at'], name='webhook_eve_process_8c85e6_idx'), models.Index(fields=['whatsapp_instance', 'event_type'], name='webhook_eve_whatsap_bc061c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text='Recipient phone number.', max_length=20)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient display name.', max_length=100, null=True)),
                ('message_content', models.TextField(blank=True, help_text='Message text content.')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, help_text='URL for media messages.', null=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When to send this message.')),
                ('priority', models.IntegerField(default=5, help_text='Message priority (1=high, 10=low).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('evolution_message_id', models.CharField(blank=True, help_text='Message ID from Evolution API.', max_length=255, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict, help_text='Full API response.')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_instance', models.ForeignKey(help_text='The WhatsApp instance to send this message from.', on_delete=django.db.models.deletion.CASCADE, related_name='queued_messages', to='whatsapp_messaging.whatsappinstance')),
            ],
            options={
                'db_table': 'message_queue',
                'ordering': ['priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='message_que_status_5c3e5e_idx'), models.Index(fields=['whatsapp_instance', 'status'], name='message_que_whatsap_cb1506_idx')],
            },
        ),
    ]
