# Generated by Django 5.0 on 2025-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_messaging', '0001_initial_standard_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagequeue',
            index=models.Index(fields=['scheduled_at'], name='wa_messageq_schedul_6754f3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagequeue',
            index=models.Index(fields=['priority'], name='wa_messageq_priorit_6ec770_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type'], name='wa_webhooke_event_t_24f462_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='wa_webhooke_created_4218f7_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['tenant_id', 'is_active'], name='wa_whatsapp_tenant__ed3562_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['tenant_id', 'status'], name='wa_whatsapp_tenant__7a3583_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['external_id'], name='wa_whatsapp_externa_631043_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['api_key'], name='wa_whatsapp_api_key_dd2be5_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappinstance',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'instance_name'), name='wa_unique_instance_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='whatsappinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('tenant_id', 'phone_number'), name='wa_unique_phone_per_tenant'),
        ),
    ]
